### ISSUE TITLE
Origem das informações para exportação

### ISSUE THREAD

**Issue by brunocc** [esusab/integracao#12]
Sou desenvolvedor na Philips Clinical Informatics onde estamos realizando a integração com os sistemas esus ab.
Temos algumas dúvidas sobre a origem de algumas informações para alimentar os arquivos xml.

As principais dúvidas são:
Quem são o remetente e o originador? Não ficou claro no dicionário de dados.
Como geramos o uuidInstalacao  e a contraChave para os dois nós do XML?

**Comment by matheusdias** [comment]
@brunocc Oi Bruno, favor entrar em contato com o 136 para a resolução de dúvidas.
